### ISSUE TITLE
سوال در مورد راست چین

### ISSUE THREAD

**Issue by Amenocy** [hamidfzm/ra-language-farsi#2]
با سلام و تشکر بابت کاری که انجام داده اید 
راستچین کردن ریاکت ادمین رو چطور حل کردید ؟

**Comment by hamidfzm** [comment]
فایل README رو اپدیت کردم. اگر جاییش رو هم متوجه نشدی بپرس

**Comment by Amenocy** [comment]
مرسی . 
من خوب و دقیق چک نکرده بودم 
ولی اون کارهایی که نوشتی نیاز هستش که این کارا هم انجام بشه 
https://material-ui.com/guides/right-to-left/

**Comment by hamidfzm** [comment]
سومی لازم نیست. خود متریال ازش استفاده میکنه

**Comment by Amenocy** [comment]
اوکی ولی من اونو اعمال کردم تا راست چین شد.
