### ISSUE TITLE
page title

### ISSUE THREAD

**Issue by mjabari** [hamidfzm/ra-language-farsi#6]
با سلام
من یه پروژه با react-admin آوردم بالا براحتی هم فارسی شد. با تشکر از شما
![screenshot](https://img.techpowerup.org/200704/screenshot-from-2020-07-03-08-33-60.png)

تنها یک مشکل داره اونم اینه که بالا سمت راست اسم پیج رو (با اینکه براش تایتل گذاشتم) هنوز انگلیسی نشون می ده
نوشته لیست users که باید می نوشت لیست کاربران
آیا راهی داره اینو درست کنم؟

**Comment by hamidfzm** [comment]
اسکرین‌شات آپلود نشده

**Comment by mjabari** [comment]
با عرض معذرت دوباره آپلود شد

**Comment by hamidfzm** [comment]
این ربطی به کتابخونه نداره داک ra-admin رو بخونی توش هست چجوری فیلدها رو ترجمه کنی
https://marmelab.com/react-admin/Translation.html
